### PR TITLE
Proposal: PrefabScope

### PR DESCRIPTION
**Pull request by galman33**
# Pull Request Template

## Description

Added a PrefabScope for automatically creating a nested scope when instantiating a prefab if available.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Currently only tested manually. I created this PR to check if this proposed feature is desirable.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] I have checked my code and corrected any misspellings
- [ ] I have checked that Reflex.GettingStarted still runs nicely

### CODE REVIEW

**Comment by gustavopsantos** [comment]
In which cases do you think a prefab scope helps? Its a need for the project youre currently working on? Maybe you can share more about your specific need.

**Comment by gustavopsantos** [comment]
@galman33 bump

**Comment by galman33** [comment]
Hey, sorry I missed your last comment.
It's for mainly used for self contained prefab, think like sub-scenes which are made using prefabs instead of scenes.
It provides more flexibility and also allows for instantiating the same prefab multiple times in the same scene with separated contexts, if that makes sense.

**Comment by gustavopsantos** [comment]
@galman33 Hmm I see, I think its gonna be a great addition. Can you finish the MR so I can review it? Remember to update documentation as well

**Comment by gustavopsantos** [comment]
Closing without activity

**Pull request closed without merging**
